version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "py2"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for python
  - package-ecosystem: "pip"
    target-branch: "py2"
    directory: "/"
    schedule:
      interval: "daily"
