#!/usr/bin/with-contenv bash

. /app/export.sh

cd /app

COUNT=0
while [ 1 ];
do
    find . -name "index.lock" -exec rm -f {} \;
    git reset --hard HEAD
    git pull
    chmod 777 .

    if [ ! -f "./data/db/sjva.db" ] ; then
        python sjva.py 0 ${COUNT} init_db
    fi

    if [ "${USE_CELERY}" == "true" ] ; then
		[ "${COUNT}" != 0 ] && s6-svc -r /var/run/s6/services/celery
        python sjva.py 0 ${COUNT}
    else
        python sjva.py 0 ${COUNT} no_celery
    fi
    
    RESULT=$?
    echo "PYTHON EXIT CODE : ${RESULT}.............."
    if [ "$RESULT" = "0" ]; then
        echo 'FINISH....'
        break
    else
        echo 'REPEAT....'
    fi 
    COUNT=`expr $COUNT + 1`
done 
