#!/usr/bin/with-contenv bash

cd /app

COUNT=0
while true;
do
    . /app/export.sh
    if [ "${USE_CELERY:-true}" = "true" ]; then
        sleep 1s
        until celery -A sjva3.celery inspect stats > /dev/null 2>&1; do
            echo "[services.d] celery is still loading. Sleeping 3s..."
            sleep 3s
        done
        echo "[services.d] celery is ready!"
    fi
    echo "[services.d] starting app..."
    python sjva3.py --repeat=${COUNT} --use_gevent=${USE_GEVENT:-true} --use_celery=${USE_CELERY:-true} --port=${SJVA_PORT:-9999}
    
    RESULT=$?
    echo "[services.d] app exited with code ${RESULT}"
    if [ "$RESULT" = "0" ]; then
        echo '[services.d] terminating app...'
        # TODO: stop services and container
        break
    else
        echo "[services.d] restarting app..."
    fi 
    COUNT=`expr $COUNT + 1`

    /etc/cont-init.d/20-config

    # restart service
    s6-svc -wr -r /var/run/s6/services/celery
    s6-svc -wr -r /var/run/s6/services/redis
done 
