#!/usr/bin/with-contenv bash

. /app/export.sh

if [ "${USE_CELERY:-true}" == "true" ]; then
	echo "*** starting redis-server@${REDIS_PORT:-46379}"
	exec s6-setuidgid abc \
		redis-server --port ${REDIS_PORT:-46379} > /dev/null 2>&1
fi

# dummy to demonize this service run
while true; do sleep 1h; done
