#!/usr/bin/with-contenv bash

echo "*** starting filebrowser"
exec s6-setuidgid abc \
	filebrowser -a 0.0.0.0 \
		-b "${FB_BASEURL:-/}" \
		-d "${FB_DATABASE:-/app/data/db/filebrowser.db}" \
		-p "${FB_PORT:-9998}" \
		-r "${FB_ROOT:-/}" \
		> /dev/null 2>&1
