name: buildx-on-schedule

on:
  watch:
    types: [started]
  schedule:
    - cron: "0 21 * * 5"

env:
  DOCKERHUB_USER: wiserain
  IMAGE_NAME: wiserain/sjva

jobs:
  buildx-on-schedule:
    runs-on: ubuntu-20.04
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    strategy:
      matrix:
        branch: [master]
        tag1: [latest]
        tag2: [latest-0.2]
        include:
          - branch: stable-0.2
            tag1: stable
            tag2: stable-0.2
          - branch: testing-py3
            tag1: testing
            tag2: testing-py3
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to docker.io
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - 
        name: Buildx and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.tag1 }}
            ${{ env.IMAGE_NAME }}:${{ matrix.tag2 }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.tag1 }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.tag2 }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
      -
        name: Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            ${{ env.IMAGE_NAME }}:${{ matrix.tag1 }}
            ${{ env.IMAGE_NAME }}:${{ matrix.tag2 }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.tag1 }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.tag2 }}
