#!/usr/bin/with-contenv bash

if [ "${USE_CELERY}" = "true" ]; then
    s6-svwait -U /var/run/service/celery
fi

cd /app

echo "*** starting SJVA..."
s6-setuidgid abc \
    python sjva3.py \
        --repeat=${SJVA_REPEAT_COUNT} \
        --use_gevent=${USE_GEVENT} \
        --use_celery=${USE_CELERY} \
        --port=${SJVA_PORT}

EXITCODE=$?
echo "*** SJVA exited with code ${EXITCODE}"
if [ "$EXITCODE" = "0" ]; then
    echo '*** terminating all services...'
    s6-svscanctl -t /var/run/service
else
    echo "*** restarting services..."
    printf $(expr $SJVA_REPEAT_COUNT + 1) > /var/run/s6/container_environment/SJVA_REPEAT_COUNT
    /etc/cont-init.d/20-config
    if [ "${USE_CELERY}" = "true" ]; then
        s6-svc -wR -r /var/run/service/celery
    fi
fi
