#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
      _____      ___      __     
     / ____|    | \ \    / /\    
    | (___      | |\ \  / /  \   
     \___ \ _   | | \ \/ / /\ \  
     ____) | |__| |  \  / ____ \ 
    |_____/ \____/    \/_/    \_\
                                 
                                 
-------------------------------------'
if [[ -f /donate.txt ]]; then
    echo '
To support the app dev(s) visit:'
    cat /donate.txt
fi
echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults

git config --global pull.ff only
git config --global init.defaultBranch master
