#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
   _____      ___      __     ____  
  / ____|    | \ \    / /\   |___ \ 
 | (___      | |\ \  / /  \    __) |
  \___ \ _   | | \ \/ / /\ \  |__ < 
  ____) | |__| |  \  / ____ \ ___) |
 |_____/ \____/    \/_/    \_\____/ 
                                    
                                    
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults

git config --global pull.ff only
git config --global init.defaultBranch main
