#!/usr/bin/with-contenv bash

if [[ ! -f /app/export.sh ]]; then
cat <<EOF >/app/export.sh
#!/bin/sh
export REDIS_PORT="46379"
export USE_CELERY="true"
export CELERY_WORKER_COUNT="2"
export RUN_FILEBROWSER="true"
export FILEBROWSER_PORT="9998"
export OS_PREFIX="Linux"
export FILEBROWSER_BASEURL="/filebrowser"
EOF
fi

mkdir -p \
  /app/bin \
  /app/data/custom

# permissions
chmod +x /app/export.sh
