#!/usr/bin/with-contenv bash
set -e

cd "${SJVA_HOME}"

# install and update SJVA
if [ -d "${SJVA_HOME}/.git" ]; then
  find "${SJVA_HOME}" -name "index.lock" -exec rm -f '{}' \;
  git reset --quiet --hard HEAD
  echo "*** checking for updates..."
  git pull origin main --allow-unrelated-histories --rebase
else
  echo "*** installing SJVA to '${SJVA_HOME}'..."
  git init --quiet > /dev/null
  git remote add origin "https://github.com/soju6jan/SJVA3.git"
  git pull --quiet origin main --depth 1
fi

# permissions
chown -R abc:abc \
  "${SJVA_HOME}"

# really necessary?
# chmod 777 .
