#!/usr/bin/with-contenv bash

# apt mirror
if [ ! -z ${APT_MIRROR+x} ] && [ -f /etc/apt/sources.list ]; then 
    sed -i "s/archive.ubuntu.com/$APT_MIRROR/g" /etc/apt/sources.list
    apt-get update -yqq
fi

# ubuntu
if [ ! -z ${INSTALL_APT_PKGS+x} ] && [ -f /usr/bin/apt ]; then
    export DEBIAN_FRONTEND=noninteractive
    IFS='|'
    INSTALL_APT_PKGS=(${INSTALL_APT_PKGS})
    # apt-get update if never done during the past 24 hours
    [ ! -d /var/lib/apt/lists/partial ] && apt-get update -yqq
    [ -z "$(find -H /var/lib/apt/lists -maxdepth 0 -mtime -1)" ] && apt-get update -yqq
    echo "*** installing apt packages: ${INSTALL_APT_PKGS[@]}"
    apt-get install -yqq --no-install-recommends \
        "${INSTALL_APT_PKGS[@]}" > /dev/null 2>&1
fi

# alpine
if [ ! -z ${INSTALL_APK_PKGS+x} ] && [ -f /sbin/apk ]; then
    IFS='|'
    INSTALL_APK_PKGS=(${INSTALL_APK_PKGS})
    echo "*** installing apk packages: ${INSTALL_APK_PKGS[@]}"
    apk add -q --no-cache \
        "${INSTALL_APK_PKGS[@]}"
fi

# python
if [ ! -z ${INSTALL_PIP_PKGS+x} ] && command -v python3 >/dev/null 2>&1; then
    IFS='|'
    INSTALL_PIP_PKGS=(${INSTALL_PIP_PKGS})
    echo "*** installing pip packages: ${INSTALL_PIP_PKGS[@]}"
    python3 -m pip -q install -U "${INSTALL_PIP_PKGS[@]}"
fi
